{% set name = "cbcflow" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cbcflow-{{ version }}.tar.gz
  sha256: 5fdf69463438d1ff726da1c66387b1125762284186cff51b425aad26d21c8623

build:
  entry_points:
    - cbcflow_print = cbcflow:print_metadata
    - cbcflow_pull = cbcflow:pull
    - cbcflow_update_from_flags = cbcflow:update
    - cbcflow_update_from_file = cbcflow:from_file
    - cbcflow_monitor_make_crondor = cbcflow:generate_crondor
    - cbcflow_monitor_make_crontab = cbcflow:generate_crontab
    - cbcflow_monitor_run = cbcflow:run_monitor
    - cbcflow_validate_library = cbcflow:validate_library
    - cbcflow_git_merge = cbcflow:cbcflow_git_merge
    - cbcflow_migrate_v2_to_v3 = cbcflow:migrate_schema_v2_to_v3
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - argcomplete
    - jsondiff
    - ligo-gracedb
    - GitPython
    - lscsoft-glue
    - coverage
    - python-benedict
    - jsonmerge
    - PyYAML
    - gwpy
    - python-crontab
    - python-gitlab
    - gwtc-tools
    - tqdm
    - asimov
    - python-dateutil
    - python-fastjsonschema

test:
  imports:
    - cbcflow
  commands:
    - pip check
    - cbcflow_print --help
    - cbcflow_pull --help
    - cbcflow_update_from_flags --help
    - cbcflow_update_from_file --help
    - cbcflow_validate_library --help
  requires:
    - pip
    - git
    - python {{ python_min }}

about:
  home: https://github.com/rhiannon-udall/cbcflow
  doc_url: https://cbc.docs.ligo.org/projects/cbcflow/
  summary: A package to document and help automate analyses of transient signals observed by the LIGO, Virgo and KAGRA gravitational-wave detectors.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - GregoryAshton
    - Rhiannon-Udall
